name: Create Branch
description: Create a bare (orphan) branch in the repository.

inputs:
  github-token:
    description: token used for creating the branch
    required: true
  name:
    description: name of the branch to create
    required: true
  readme:
    description: contents of the markdown README file which gets created
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: git-commit
  color: gray-dark