name: Create Branch
description: Create a bare (orphan) branch in the repository.

inputs:
  name:
    description: 'name of the branch to create'
    required: true

runs:
  using: 'node12'
  main: 'action.js'

branding:
  icon: git-commit
  color: gray-dark
